dist: trusty
sudo: false

language: node_js
node_js:
  - "11.0"

cache:
  directories:
    - node_modules
branches:
  only:
    - master

install:
- npm install

script:
- ng build --base-href https://hks9211.github.io/fundooClient/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/fundooClient
  on:
    branch: master
