language: node_js
node_js:
- 8.9.0

install:
- npm install
script:
- ng build --base-href https://hks9211.github.io/fundooClient/
deploy:
  provider: heroku
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master


