dist: trusty
sudo: false

language: node_js
node_js:
  - "11.0"

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.npm"

branches:
  only:
    - master

install:
- npm install

script:
  - npm run test-single-run -- --browsers ChromeHeadless
  - (npm start > /dev/null &) && npm run protractor -- --capabilities.chromeOptions.args headless

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/fundooClient
  on:
    branch: master

# script:
# - ng build --base-href https://hks9211.github.io/fundooClient/


