language: node_js
node_js:
- 8.9.0

install:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

# script:
# - ng build --base-href https://hks9211.github.io/fundooClient/


