language: node_js
node_js:
- 8.9.0
cache: npm
install:
- npm install
script:
- ng build --base-href https://hks9211.github.io/fundooClient/
deploy:
  provider: heroku
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  app: fundoo
  api_key:
    secure: hvFKepgxwIpMm1GbVf93SUSMUpdyhT5PWnjaajTNF/paBrnWc0iwUfqfbW3JKLcFN7oLxZ8CFRPUCgesQvaqPREwzHQ5Kn8qtG1FFVMlKIoC/tWFf41jozxgT8lQWdq4XI4E0bmzkiKFkE0JmETmSVkvYJU97yHa14wnCxj58EAYgBA5dW887x+P53rTo2MZofqgLmhmMkxn4FAOs8sZLH6X/GtiLNX/4vaeXQKwCLtZGrubL39j4rbcQ4531oCBlpb3t42Kg+XE/kwBNoRXK6wvG2k+6N1JU7Sm0BaQ30ejQHTR9JLMk07WRB43ShpdJdmoIR63uI6xV90Ph6mwU/wewZQQ2d4LQBGCgpgmncwqBQnfZDnFXXiE8vGR0ARUs8hFjwFBOEFwNMIiyFRPgNzK/lyHqQQWd2X1KLIldnJ/EhoBoHpUDkNdWxhNC6OZ1zD/Md+1kOORhXs/jA4hNMKxLpHekQoLmXwQZk3x/55A0HQNWEApzlsZdTP4W/RmWuR62F1KTM3PNDeW7jWt6f/yw9VZgbq3jjfBQ8WypymnWLhFBocRlbXELNJWMSdUFqFEb4E5JiD+8Fm/7VS6EqMdjCiTIH6nyqbabgRaEbALiXwaGpojplW8Sl2QlMkH9ftcTgQyVhdzZBUUTYTzN4J0P4QF/g6L9kKoq3dzUu8=

