language: node_js
node_js:
- 8.9.0
cache: npm

install:
- npm install

script:
- ng build --prod --base-href https://hks9211.github.io/fundooClient/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
