language: node_js
node_js:
- 8.9.0
cache: npm
install:
- npm install
script:
- ng build --base-href https://hks9211.github.io/fundooClient/
deploy:
  provider: heroku
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  app: fundoo
  api_key:
    secure: O5BxBfAGeKa9WIY+ZWEB89cPzlv/8P2jc9SW3zE8Tq+aa3pD9Sq69Z7NYa2/9dsKlsMv67+Fsyhpo0rAHpemJv+KOG1Z4K9TdTGoi3wPunPzCMBZR++/6mgP8r7r0165f6o9dS/HUKfblrqOPfwRUpe0X6AJpqyR2pIh1FdQz0dflgwk8khngglrTXigojRHu+HXAG3rGeLwURBLIMZ36L+3YDjN+tUgwn04O5fe7lkF5Qizg46aDyoH7Lm8gxPrPBGPlCgah00nYkP4pvkwgvMMZG5q1gad8Vm+l/1OJOxxvi8jP8+LPDGmrzmwO1lGL9GbJvowrPhijqT9QmJqHCt0nEQ9/bYPvrJ9zYxmMMw4cR3sNAnSYeUI0//IcdJ0W4mmIqiTjI7w+PMhN8HKDGDvfM+yxh5VksOo13gU+FDIj7X1HSpOnnwTPgOGJ6MvU2rWW/T+cgyOfzyhWIAO70LbbnpdVkJz5CVxUdJWeQ2syM49Y5sYRjmhYy36BDMcSGYXzWor0WjiDCup9Io5o8uoqpG+7D38IYejdyUZIVLtOzucyGoRHJ2zz9y6NJwZPv8lBrkHs3GfMPyYRy9udQk8yq5OrkurwzX2v6sdJA1Q93ow1stM3n1Hp+rEIODvm4n1S8Da77X3uXEE2KI6GTfDmoOrydSQt9iq1IkopO8=
